language: php

sudo: false

php:
  - 7.3
  - 7.4
  - 8.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - travis_retry phpenv rehash

script:
  - composer run-script test
